PL/Models/BidViewModels.cs
namespace PL.Models
{
    public class MakeBidViewModel
    {
        public string ClientId { get; set; }
        public int ProductId { get; set; }
        public decimal SuggestedPrice { get; set; }
        public decimal InitialPrice { get; set; }
        public string BidLastCustomerId { get; set; }
        public string ProductOwnerId { get; set; }
    }

    public class BidProductViewModel
    {
        public int Id { get; set; }
        public decimal SuggesterPrice { get; set; }
        public decimal InitialPrice { get; set; }
        public string CategoryTitle { get; set; }
        public string ProductDescription { get; set; }
        public string ProductName { get; set; }
    }
}

PL/Controllers/BidController.cs
using BLL.DTO;
using PL.Models;
using PL.Helpers;
using PL.Filters;
using AutoMapper;
using BLL.Interfaces;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace PL.Controllers
{
    [CustomAuthorize]
    public class BidController : Controller
    {
        readonly IMapper _mapper;
        const string ERRORS = "errors";
        readonly IBidService _bidService;
        readonly IProductService _productService;

        public BidController(IBidService serv, IMapper mapper, IProductService pServ)
        {
            _mapper = mapper;
            _bidService = serv;
            _productService = pServ;
        }

        public async Task<ActionResult> MakeBid(int? id)
        {
            var initialPrice = await _bidService.GetProductInitialPriceAsync(id);
            var lastCustomerId = await _bidService.GetLastCustomerIdAsync(id);
            var ownerId = await _bidService.GetProductOwnerId(id);
            var model = new MakeBidViewModel()
            {
                ProductId = id ?? 0,
                InitialPrice = initialPrice,
                BidLastCustomerId = lastCustomerId,
                ProductOwnerId = ownerId
            };
            return View(model);
        }

        public async Task<ActionResult> ConfirmBid(MakeBidViewModel bid)
        {
            if (ModelState.IsValid)
            {
                var product = await _productService.GetParticularProductByIdAsync(bid.ProductId);
                var generalProduct = await _productService.GetGeneralProductByIdAsync(product.GeneralProductId);
                var bidProduct = new BidProductViewModel
                {
                    CategoryTitle = generalProduct.Category.Title,
                    InitialPrice = product.CurrentPrice,
                    ProductDescription = product.Description,
                    ProductName = generalProduct.Name,
                    SuggesterPrice = bid.SuggestedPrice,
                    Id = bid.ProductId
                };
                TempData[nameof(bid)] = bid;
                return View(bidProduct);
            }
            TempData[nameof(ERRORS)] = ErrorHelper.GetErrorList(ModelState.Values);
            return RedirectToAction(nameof(MakeBid), new { id = bid.ProductId });
        }

        public async Task<ActionResult> SaveBid(MakeBidViewModel bid)
        {
            bid = TempData[nameof(bid)] as MakeBidViewModel ?? bid;
            var bidDto = _mapper.Map<BidDTO>(bid);
            await _bidService.MakeBidAsync(bidDto);
            return View();
        }
    }
}

PL/Views/Bid/ConfirmBid.cshtml
@model PL.Models.BidProductViewModel

<h2 class="text-center">Confirm bid</h2>

<div>
    <dl class="dl-horizontal">

        <dt>@Html.DisplayNameFor(model => model.CategoryTitle)</dt>
        <dd>@Html.DisplayFor(model => model.CategoryTitle)</dd>

        <dt>@Html.DisplayNameFor(model => model.ProductName)</dt>
        <dd>@Html.DisplayFor(model => model.ProductName)</dd>
        
        <dt>@Html.DisplayNameFor(model => model.InitialPrice)</dt>
        <dd>@Html.DisplayFor(model => model.InitialPrice)</dd>

        <dt>@Html.DisplayNameFor(model => model.SuggesterPrice)</dt>
        <dd>@Html.DisplayFor(model => model.SuggesterPrice)</dd>

        <dt>@Html.DisplayNameFor(model => model.ProductDescription)</dt>
        <dd>@Html.DisplayFor(model => model.ProductDescription)</dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "MakeBid", new { id = Model.Id }) |
    @Html.ActionLink("Back to categories", "Index", "Home") |
    @Html.ActionLink("Confirm", "SaveBid")
</p>

PL/Views/Bid/MakeBid.cshtml
@model PL.Models.MakeBidViewModel
@using Microsoft.AspNet.Identity

<h2 class="text-center">Create a new bid.</h2>

@using (Html.BeginForm("ConfirmBid", "Bid", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
 {
    @Html.AntiForgeryToken()
    @Html.Partial("_InlineErrorPartial")

    <div class="form-group text-success">
        @Html.LabelFor(m => m.InitialPrice, new { @class = "col-md-2 text-right" })
        <div class="col-md-10">
            @Html.DisplayFor(m => m.InitialPrice, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SuggestedPrice, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="number" name=@nameof(Model.SuggestedPrice) required class="form-control" pattern="[0-8]" size="2" />
        </div>
    </div>

    <input data-val="true"
           name="ClientId"
           type="hidden"
           value="@User.Identity.GetUserId()" />

    @Html.HiddenFor(m => m.ProductId)
    @Html.HiddenFor(m => m.InitialPrice)
    @Html.HiddenFor(m => m.ProductOwnerId)
    @Html.HiddenFor(m => m.BidLastCustomerId)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Make bid" />
        </div>
    </div>
 }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PL/Views/Bid/SaveBid.cshtml
<h2 class="text-success">Bid successfully created and saved to database</h2>

<hr />
<img src="~/Assets/Img/Success/okay.png" alt="Success" class="img-responsive center-block" style="height: 50vh" />

<p>
    @Html.ActionLink("Continue shopping", "Index", "Home")
</p>